#!/usr/bin/env bash

CISCO_SPLIT_INC=1
CISCO_SPLIT_INC_0_ADDR="${SERVER_ROUTE%/*}"
CISCO_SPLIT_INC_0_MASKLEN="${SERVER_ROUTE#*/}"
CISCO_SPLIT_INC_0_PROTOCOL=0
CISCO_SPLIT_INC_0_SPORT=0
CISCO_SPLIT_INC_0_DPORT=0

source /usr/share/vpnc-scripts/vpnc-script
